---
- name: Provision Google Cloud VM
  hosts: webserver
  become: yes
  vars:
    ansible_user: "{{ lookup('env', 'GCP_USER') }}"
    cf_token: "{{ lookup('env', 'CF_API_TOKEN') }}"
    cf_data: "{{ lookup('env', 'CF_RECORDS_DATA') }}"
    home_ip: "{{ lookup('env', 'MY_HOME_IP') }}"

  tasks:
    - name: 1. Install Software
      apt:
        pkg: [nginx, git, ufw, ssl-cert, cron, fail2ban, snapd]
        update_cache: yes

    - name: 2. Set up Firewall (UFW)
      ufw:
            rule: allow
            port: "{{ item.port }}"
            from_ip: "{{ item.from }}"
      loop:
            - { port: '80', from: 'any' }
            - { port: '443', from: 'any' }
            - { port: '22', from: "{{ home_ip }}" } # Locked to your Home IP

    - name: 3. Enable Firewall
      ufw:
        state: enabled

    - name: 4. Clone Web Files
      git:
        repo: "https://github.com/Open-DCF/OpenDCF-Web.git"
        dest: "/var/www/opendcf-web"
        force: yes

    - name: 5. Configure Nginx
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/sites-available/opendcf
      notify: Restart Nginx

    - name: 6. Enable Site & Remove Default
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
    
    - name: 7. Link New Site
      file:
        src: /etc/nginx/sites-available/opendcf
        dest: /etc/nginx/sites-enabled/opendcf
        state: link

    - name: 8. Setup DDNS Script
      template:
        src: update-ddns.sh
        dest: /usr/local/bin/update-ddns
        mode: '0755'

    - name: 9. Schedule DDNS to run every 5 mins
      cron:
        name: "Update Cloudflare IP"
        minute: "*/5"
        job: "/usr/local/bin/update-ddns"

    - name: 10. Create SSL Directory
      file:
        path: /etc/nginx/ssl
        state: directory
        mode: '0755'

    - name: 11. Copy Cloudflare Origin Certificates
      copy:
        src: "/.certificates/{{ item }}"
        dest: "/etc/nginx/ssl/{{ item }}"
        mode: '0600'
      loop:
        - io-cert.crt
        - io-cert.key
        - org-cert.crt
        - org-cert.key
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted